# Data
min_word_cnt: 5

geek_max_sent_num: 20
job_max_sent_num: 20
geek_max_sent_len: 30
job_max_sent_len: 30

# Model
embedding_size: 64
LSTM_hidden_dim: 64

# Training
learning_rate: 0.0003

# General
train_batch_size: 200
eval_batch_size: 4096