# Model
embedding_size: 128
n_layers: 3
reg_weight: 1e-05
mutual_weight: 0.1
temperature: 0.1

ADD_BERT: True
BERT_embedding_size: 768
BERT_output_size: 32

# Training
learning_rate: 0.001

# General
train_batch_size: 4096
eval_batch_size: 4096

