# Data
min_word_cnt: 5

geek_max_sent_num: 20
job_max_sent_num: 20
geek_max_sent_len: 30
job_max_sent_len: 30

# Model
BERT_embedding_size: 768
embedding_size: 64

# Training
learning_rate: 0.0003

# General
train_batch_size: 1024
eval_batch_size: 1024
