# Data
min_word_cnt: 5

geek_max_sent_num: 5
job_max_sent_num: 5
geek_max_sent_len: 10
job_max_sent_len: 10

# Model
embedding_size: 100

# Training
learning_rate: 0.0003

# General
train_batch_size: 2048
eval_batch_size: 4096
