# Model
embedding_size: 256
n_layers: 2
# dropout: 0.2
ADD_BERT: True
BERT_embedding_size: 768
BERT_output_size: 32

# Training
learning_rate: 0.0001

# General
train_batch_size: 4096
eval_batch_size: 4096

