# GCN part
# embedding_size: 128
embedding_size: 64 # 开聊加入训练数据之后 256 跑不起来
# GCN_embedding_size: 128
GCN_layers: 2

# BERT part
BERT_embedding_size: 768
BERT_dropout: 0.2
BERT_output_size: 64
ADD_BERT: True

# Training
learning_rate: 0.00001

# General
train_batch_size: 4096
eval_batch_size: 4096

