# Model
# embedding_size: 64
mf_embedding_size: 64
mlp_embedding_size: 64
mlp_hidden_size: [32,8]

ADD_BERT: False
BERT_embedding_size: 768
BERT_output_size: 32

dropout: 0.2

# Training
learning_rate: 0.0001

# General
train_batch_size: 4096
eval_batch_size: 4096
