# Model
embedding_size: 256
mf_embedding_size: 128
mlp_embedding_size: 128
mlp_hidden_size: [128,64]
mf_train: True
mlp_train: True

ADD_BERT: True
BERT_embedding_size: 768
BERT_output_size: 32

dropout: 0.2

# Training
learning_rate: 0.00001

# General
train_batch_size: 4096
eval_batch_size: 4096
