# Model
embedding_size: 128
hidden_size: 32
dropout: 0.2
num_layers: 1


BERT_embedding_size: 768
BERT_output_size: 32

# Training
learning_rate: 0.0001

# General
train_batch_size: 2048
eval_batch_size: 4096

