# Model
embedding_size: 64
n_layers: 3
reg_weight: 1e-05
# hidden_size: 8
# dropout: 0.2

# Training
learning_rate: 0.001
# add_sample_rate: 0.3

# General
train_batch_size: 4096
eval_batch_size: 4096

